image: vratislav/gitlab-ci-fastlane-android

stages:
  - build
  - test
#  - deploy

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/apk/develop/debug/app-develop-debug.apk


debugTests:
  stage: test
  script:
    - ./gradlew test



#deploy_internal:
#  stage: deploy
#  only:
#    - master
#  script:
#    - fastlane slack_build
