name: Android Pull Request & Master CI & CD to Firebase

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/develop/debug/app-develop-debug.apk
  build:
    name: Upload apk to App Tester
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: deploy
        run: bash ./gradlew assembleDebug
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.2
        with:
          appId: '1:479003587507:android:af8d8cd97dc416a45611c6'
          token: '1//0dZndJIJMS3XmCgYIARAAGA0SNwF-L9IrAfCz-l5q96FkyI5RBRlwHp0B7Tfr551aJBniygTqUQSFEuRbfUopFinFzPOgIXrZwRI'
          groups: testers
          file: app/build/outputs/apk/develop/debug/app-develop-debug.apk

